In [1]:
import polars as pl

In [2]:
df = pl.read_parquet(
    '/Users/evrins/workspace/python/dnf_gm_tool/data/c5ae9f89/quests.parquet'
)
df

shape: (3_009, 7)
┌───────┬───────────────┬───────────────┬───────────────┬────────────┬──────────────┬──────────────┐
│ id    ┆ name          ┆ json          ┆ grade         ┆ difficulty ┆ quest_type   ┆ int_data     │
│ ---   ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---          ┆ ---          │
│ i64   ┆ str           ┆ str           ┆ str           ┆ str        ┆ str          ┆ list[i64]    │
╞═══════╪═══════════════╪═══════════════╪═══════════════╪════════════╪══════════════╪══════════════╡
│ 1     ┆ 神圣的守护者  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [26, -1,     │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 240]         │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 2     ┆ 天空之城开拓  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [17, -1, 90] │
│       ┆ 者            ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 3     ┆ 烈焰征服者    ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [seeking]    ┆ [3073, 100]  │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆              ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 4     ┆ 精灵的魔法阵  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [seeking]    ┆ [4024, 40]   │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆              ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 5     ┆ 人偶的诱惑    ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [seeking]    ┆ [4025, 1]    │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆              ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ …     ┆ …             ┆ …             ┆ …             ┆ …          ┆ …            ┆ …            │
│ 20731 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3538, -1,   │
│       ┆ 巨龙盘踞之地  ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆ 1]           │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20732 ┆ 洞穴探索者    ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [seeking]    ┆ [10002514,   │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆              ┆ 7]           │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 20733 ┆ 燃烧的念气    ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [seeking]    ┆ [10002517,   │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆              ┆ 15]          │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 20734 ┆ 灭龙者        ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [seeking]    ┆ [10002518,   │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆              ┆ 21]          │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 20735 ┆ [限时]极限挑  ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [condition   ┆ [3539, 0,    │
│       ┆ 战 - 屠龙     ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 360]         │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
└───────┴───────────────┴───────────────┴───────────────┴────────────┴──────────────┴──────────────┘

In [8]:
df.select(pl.col('quest_type')).unique().sort(by='quest_type')

shape: (20, 1)
┌────────────────────┐
│ quest_type         │
│ ---                │
│ str                │
╞════════════════════╡
│ [amplify item]     │
│ [assault count]    │
│ [check time]       │
│ [clear map]        │
│ [clear quest]      │
│ …                  │
│ [seeking]          │
│ [send chatting]    │
│ [ui click]         │
│ [use fortune coin] │
│ [use item]         │
└────────────────────┘

In [5]:
df.filter(pl.col('quest_type') == '[get item]')

shape: (16, 7)
┌──────┬──────┬───────────────────────────┬─────────┬────────────┬────────────┬────────────────────┐
│ id   ┆ name ┆ json                      ┆ grade   ┆ difficulty ┆ quest_type ┆ int_data           │
│ ---  ┆ ---  ┆ ---                       ┆ ---     ┆ ---        ┆ ---        ┆ ---                │
│ i64  ┆ str  ┆ str                       ┆ str     ┆ str        ┆ str        ┆ list[i64]          │
╞══════╪══════╪═══════════════════════════╪═════════╪════════════╪════════════╪════════════════════╡
│ 6532 ┆      ┆ {"[check count]":         ┆ [title] ┆            ┆ [use item] ┆ [1, 3037, 1]       │
│      ┆      ┆ [10000], "[g…             ┆         ┆            ┆            ┆                    │
│ 6543 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [17, 2600263, … 1] │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6544 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [22, 2600265, … 1] │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6569 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [23, 7138, … 1]    │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6570 ┆      ┆ {"[check count]": [300],  ┆ [title] ┆            ┆ [use item] ┆ [11, 7139, … 1]    │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ …    ┆ …    ┆ …                         ┆ …       ┆ …          ┆ …          ┆ …                  │
│ 6578 ┆      ┆ {"[check count]": [500],  ┆ [title] ┆            ┆ [use item] ┆ [2, 1234, … 1]     │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6579 ┆      ┆ {"[check count]": [500],  ┆ [title] ┆            ┆ [use item] ┆ [50, 2600000, … 1] │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6598 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [2, 36, … 1]       │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6702 ┆      ┆ {"[check count]": [60],   ┆ [title] ┆            ┆ [use item] ┆ [5, 8227, … 1]     │
│      ┆      ┆ "[grad…                   ┆         ┆            ┆            ┆                    │
│ 6707 ┆      ┆ {"[check count]": [12],   ┆ [title] ┆            ┆ [use item] ┆ [1, 8394, 1]       │
│      ┆      ┆ "[grad…                   ┆         ┆            ┆            ┆                    │
└──────┴──────┴───────────────────────────┴─────────┴────────────┴────────────┴────────────────────┘

In [6]:
df.filter(pl.col('quest_type') == '[condition under clear]')

shape: (792, 7)
┌───────┬───────────────┬───────────────┬───────────────┬────────────┬──────────────┬──────────────┐
│ id    ┆ name          ┆ json          ┆ grade         ┆ difficulty ┆ quest_type   ┆ int_data     │
│ ---   ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---          ┆ ---          │
│ i64   ┆ str           ┆ str           ┆ str           ┆ str        ┆ str          ┆ list[i64]    │
╞═══════╪═══════════════╪═══════════════╪═══════════════╪════════════╪══════════════╪══════════════╡
│ 1     ┆ 神圣的守护者  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [26, -1,     │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 240]         │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 2     ┆ 天空之城开拓  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [17, -1, 90] │
│       ┆ 者            ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 11    ┆ 冰心之魂      ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [41, 2, 240] │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 15    ┆ 索西雅的灾星  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [140, 2, 1]  │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 22    ┆ 调查GBL神殿   ┆ {"[grade]":   ┆ [epic]        ┆ W          ┆ [condition   ┆ [21, -1]     │
│       ┆               ┆ ["[epic]"],   ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ "[diff…       ┆               ┆            ┆              ┆              │
│ …     ┆ …             ┆ …             ┆ …             ┆ …          ┆ …            ┆ …            │
│ 20728 ┆ 虚祖圣地 -    ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [condition   ┆ [3538, -1,   │
│       ┆ 与巨龙战斗    ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 1]           │
│       ┆ (2/2)         ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 20729 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3536, 2, 1] │
│       ┆ 念气修炼场    ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20730 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3537, 2, 1] │
│       ┆ 念气洞穴深处  ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20731 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3538, -1,   │
│       ┆ 巨龙盘踞之地  ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆ 1]           │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20735 ┆ [限时]极限挑  ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [condition   ┆ [3539, 0,    │
│       ┆ 战 - 屠龙     ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 360]         │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
└───────┴───────────────┴───────────────┴───────────────┴────────────┴──────────────┴──────────────┘

In [10]:
df.filter(pl.col('quest_type') == '[amplify item]')

shape: (4, 7)
┌──────┬──────────┬──────────────────┬───────────────┬────────────┬────────────────┬───────────────┐
│ id   ┆ name     ┆ json             ┆ grade         ┆ difficulty ┆ quest_type     ┆ int_data      │
│ ---  ┆ ---      ┆ ---              ┆ ---           ┆ ---        ┆ ---            ┆ ---           │
│ i64  ┆ str      ┆ str              ┆ str           ┆ str        ┆ str            ┆ list[i64]     │
╞══════╪══════════╪══════════════════╪═══════════════╪════════════╪════════════════╪═══════════════╡
│ 172  ┆ 强化武器 ┆ {"[grade]": ["[a ┆ [achievement] ┆ Z          ┆ [amplify item] ┆ [4, -1, … 10] │
│      ┆          ┆ chievement]"],…  ┆               ┆            ┆                ┆               │
│ 6589 ┆          ┆ {"[check         ┆ [title]       ┆            ┆ [amplify item] ┆ [-1, 2, -1]   │
│      ┆          ┆ count]": [20],   ┆               ┆            ┆                ┆               │
│      ┆          ┆ "[grad…          ┆               ┆            ┆                ┆               │
│ 6590 ┆          ┆ {"[check         ┆ [title]       ┆            ┆ [amplify item] ┆ [10, 2, -1]   │
│      ┆          ┆ count]": [30],   ┆               ┆            ┆                ┆               │
│      ┆          ┆ "[grad…          ┆               ┆            ┆                ┆               │
│ 6591 ┆          ┆ {"[grade]":      ┆ [title]       ┆            ┆ [amplify item] ┆ [15, -1, -1]  │
│      ┆          ┆ ["[title]"],     ┆               ┆            ┆                ┆               │
│      ┆          ┆ "[lev…           ┆               ┆            ┆                ┆               │
└──────┴──────────┴──────────────────┴───────────────┴────────────┴────────────────┴───────────────┘

In [11]:
df.filter(pl.col('quest_type') == '[assault count]')

shape: (1, 7)
┌──────┬──────┬──────────────────────────┬─────────┬────────────┬─────────────────┬───────────┐
│ id   ┆ name ┆ json                     ┆ grade   ┆ difficulty ┆ quest_type      ┆ int_data  │
│ ---  ┆ ---  ┆ ---                      ┆ ---     ┆ ---        ┆ ---             ┆ ---       │
│ i64  ┆ str  ┆ str                      ┆ str     ┆ str        ┆ str             ┆ list[i64] │
╞══════╪══════╪══════════════════════════╪═════════╪════════════╪═════════════════╪═══════════╡
│ 6599 ┆      ┆ {"[grade]": ["[title]"], ┆ [title] ┆            ┆ [assault count] ┆ []        │
│      ┆      ┆ "[lev…                   ┆         ┆            ┆                 ┆           │
└──────┴──────┴──────────────────────────┴─────────┴────────────┴─────────────────┴───────────┘

In [17]:
(
    df.filter(pl.col('name') != '')
    .group_by(pl.col('quest_type'))
    .agg(count=pl.col('quest_type').count())
    .sort(by='count')
)

shape: (10, 2)
┌─────────────────────────┬───────┐
│ quest_type              ┆ count │
│ ---                     ┆ ---   │
│ str                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ [amplify item]          ┆ 1     │
│ [disjoint item]         ┆ 1     │
│ [seek n meet npc]       ┆ 2     │
│ [custom quest]          ┆ 17    │
│ [clear map]             ┆ 71    │
│ [hunt monster]          ┆ 151   │
│ [meet npc]              ┆ 359   │
│ [hunt enemy]            ┆ 518   │
│ [condition under clear] ┆ 732   │
│ [seeking]               ┆ 982   │
└─────────────────────────┴───────┘

In [15]:
df.filter(pl.col('quest_type') == '[get score]')

shape: (6, 7)
┌──────┬──────┬─────────────────────────────────┬─────────┬────────────┬─────────────┬───────────┐
│ id   ┆ name ┆ json                            ┆ grade   ┆ difficulty ┆ quest_type  ┆ int_data  │
│ ---  ┆ ---  ┆ ---                             ┆ ---     ┆ ---        ┆ ---         ┆ ---       │
│ i64  ┆ str  ┆ str                             ┆ str     ┆ str        ┆ str         ┆ list[i64] │
╞══════╪══════╪═════════════════════════════════╪═════════╪════════════╪═════════════╪═══════════╡
│ 6533 ┆      ┆ {"[check count]": [500], "[gra… ┆ [title] ┆            ┆ [get score] ┆ [5, 1]    │
│ 6534 ┆      ┆ {"[grade]": ["[title]"], "[lev… ┆ [title] ┆            ┆ [get score] ┆ [10, 985] │
│ 6535 ┆      ┆ {"[grade]": ["[title]"], "[lev… ┆ [title] ┆            ┆ [get score] ┆ [0, 888]  │
│ 6700 ┆      ┆ {"[grade]": ["[title]"], "[lev… ┆ [title] ┆            ┆ [get score] ┆ [0, 16]   │
│ 6701 ┆      ┆ {"[check count]": [16], "[grad… ┆ [title] ┆            ┆ [get score] ┆ [4, 1]    │
│ 6708 ┆      ┆ {"[check count]": [777], "[gra… ┆ [title] ┆            ┆ [get score] ┆ [4, 1]    │
└──────┴──────┴─────────────────────────────────┴─────────┴────────────┴─────────────┴───────────┘

In [16]:
df.filter(pl.col('quest_type') == '[use item]')

shape: (16, 7)
┌──────┬──────┬───────────────────────────┬─────────┬────────────┬────────────┬────────────────────┐
│ id   ┆ name ┆ json                      ┆ grade   ┆ difficulty ┆ quest_type ┆ int_data           │
│ ---  ┆ ---  ┆ ---                       ┆ ---     ┆ ---        ┆ ---        ┆ ---                │
│ i64  ┆ str  ┆ str                       ┆ str     ┆ str        ┆ str        ┆ list[i64]          │
╞══════╪══════╪═══════════════════════════╪═════════╪════════════╪════════════╪════════════════════╡
│ 6532 ┆      ┆ {"[check count]":         ┆ [title] ┆            ┆ [use item] ┆ [1, 3037, 1]       │
│      ┆      ┆ [10000], "[g…             ┆         ┆            ┆            ┆                    │
│ 6543 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [17, 2600263, … 1] │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6544 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [22, 2600265, … 1] │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6569 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [23, 7138, … 1]    │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6570 ┆      ┆ {"[check count]": [300],  ┆ [title] ┆            ┆ [use item] ┆ [11, 7139, … 1]    │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ …    ┆ …    ┆ …                         ┆ …       ┆ …          ┆ …          ┆ …                  │
│ 6578 ┆      ┆ {"[check count]": [500],  ┆ [title] ┆            ┆ [use item] ┆ [2, 1234, … 1]     │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6579 ┆      ┆ {"[check count]": [500],  ┆ [title] ┆            ┆ [use item] ┆ [50, 2600000, … 1] │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6598 ┆      ┆ {"[check count]": [100],  ┆ [title] ┆            ┆ [use item] ┆ [2, 36, … 1]       │
│      ┆      ┆ "[gra…                    ┆         ┆            ┆            ┆                    │
│ 6702 ┆      ┆ {"[check count]": [60],   ┆ [title] ┆            ┆ [use item] ┆ [5, 8227, … 1]     │
│      ┆      ┆ "[grad…                   ┆         ┆            ┆            ┆                    │
│ 6707 ┆      ┆ {"[check count]": [12],   ┆ [title] ┆            ┆ [use item] ┆ [1, 8394, 1]       │
│      ┆      ┆ "[grad…                   ┆         ┆            ┆            ┆                    │
└──────┴──────┴───────────────────────────┴─────────┴────────────┴────────────┴────────────────────┘

In [18]:
df.filter(pl.col('quest_type') == '[clear map]')

shape: (71, 7)
┌──────┬──────────────────┬─────────────────┬───────────────┬────────────┬─────────────┬───────────┐
│ id   ┆ name             ┆ json            ┆ grade         ┆ difficulty ┆ quest_type  ┆ int_data  │
│ ---  ┆ ---              ┆ ---             ┆ ---           ┆ ---        ┆ ---         ┆ ---       │
│ i64  ┆ str              ┆ str             ┆ str           ┆ str        ┆ str         ┆ list[i64] │
╞══════╪══════════════════╪═════════════════╪═══════════════╪════════════╪═════════════╪═══════════╡
│ 157  ┆ 觉醒 -           ┆ {"[grade]": ["[ ┆ [achievement] ┆ D          ┆ [clear map] ┆ [30030]   │
│      ┆ 末日审判者 (2/4) ┆ achievement]"], ┆               ┆            ┆             ┆           │
│      ┆                  ┆ …               ┆               ┆            ┆             ┆           │
│ 904  ┆ 觉醒 - 暴风眼    ┆ {"[grade]": ["[ ┆ [achievement] ┆ D          ┆ [clear map] ┆ [30030]   │
│      ┆ (2/4)            ┆ achievement]"], ┆               ┆            ┆             ┆           │
│      ┆                  ┆ …               ┆               ┆            ┆             ┆           │
│ 910  ┆ 觉醒 - 毒王      ┆ {"[grade]": ["[ ┆ [achievement] ┆ D          ┆ [clear map] ┆ [30030]   │
│      ┆ (2/4)            ┆ achievement]"], ┆               ┆            ┆             ┆           │
│      ┆                  ┆ …               ┆               ┆            ┆             ┆           │
│ 915  ┆ 觉醒 - 百花缭乱  ┆ {"[grade]": ["[ ┆ [achievement] ┆ D          ┆ [clear map] ┆ [30030]   │
│      ┆ (2/4)            ┆ achievement]"], ┆               ┆            ┆             ┆           │
│      ┆                  ┆ …               ┆               ┆            ┆             ┆           │
│ 920  ┆ 觉醒 - 武神      ┆ {"[grade]": ["[ ┆ [achievement] ┆ D          ┆ [clear map] ┆ [30030]   │
│      ┆ (2/4)            ┆ achievement]"], ┆               ┆            ┆             ┆           │
│      ┆                  ┆ …               ┆               ┆            ┆             ┆           │
│ …    ┆ …                ┆ …               ┆ …             ┆ …          ┆ …           ┆ …         │
│ 4580 ┆ 解救格兰迪站长   ┆ {"[grade]":     ┆ [epic]        ┆ W          ┆ [clear map] ┆ [14009,   │
│      ┆                  ┆ ["[epic]"],     ┆               ┆            ┆             ┆ 10418]    │
│      ┆                  ┆ "[diff…         ┆               ┆            ┆             ┆           │
│ 4589 ┆ 战友再聚首       ┆ {"[grade]":     ┆ [epic]        ┆ X          ┆ [clear map] ┆ [15421]   │
│      ┆                  ┆ ["[epic]"],     ┆               ┆            ┆             ┆           │
│      ┆                  ┆ "[diff…         ┆               ┆            ┆             ┆           │
│ 4590 ┆ 柯维的真正实力   ┆ {"[grade]":     ┆ [epic]        ┆ W          ┆ [clear map] ┆ [15423]   │
│      ┆                  ┆ ["[epic]"],     ┆               ┆            ┆             ┆           │
│      ┆                  ┆ "[diff…         ┆               ┆            ┆             ┆           │
│ 4591 ┆ 飞燕的真正实力   ┆ {"[grade]":     ┆ [epic]        ┆ X          ┆ [clear map] ┆ [15422]   │
│      ┆                  ┆ ["[epic]"],     ┆               ┆            ┆             ┆           │
│      ┆                  ┆ "[diff…         ┆               ┆            ┆             ┆           │
│ 4592 ┆ 最强的精锐部队   ┆ {"[grade]":     ┆ [epic]        ┆ X          ┆ [clear map] ┆ [15425]   │
│      ┆                  ┆ ["[epic]"],     ┆               ┆            ┆             ┆           │
│      ┆                  ┆ "[diff…         ┆               ┆            ┆             ┆           │
└──────┴──────────────────┴─────────────────┴───────────────┴────────────┴─────────────┴───────────┘

In [21]:
df.select(pl.col('grade')).unique().sort(by='grade')

shape: (10, 1)
┌──────────────────┐
│ grade            │
│ ---              │
│ str              │
╞══════════════════╡
│ [achievement]    │
│ [common unique]  │
│ [daily random]   │
│ [daily]          │
│ [epic]           │
│ [normaly repeat] │
│ [special daily]  │
│ [title]          │
│ [training]       │
│ [urgent]         │
└──────────────────┘

In [22]:
df.filter(pl.col('quest_type') == '[condition under clear]')

shape: (792, 7)
┌───────┬───────────────┬───────────────┬───────────────┬────────────┬──────────────┬──────────────┐
│ id    ┆ name          ┆ json          ┆ grade         ┆ difficulty ┆ quest_type   ┆ int_data     │
│ ---   ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---          ┆ ---          │
│ i64   ┆ str           ┆ str           ┆ str           ┆ str        ┆ str          ┆ list[i64]    │
╞═══════╪═══════════════╪═══════════════╪═══════════════╪════════════╪══════════════╪══════════════╡
│ 1     ┆ 神圣的守护者  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [26, -1,     │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 240]         │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 2     ┆ 天空之城开拓  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [17, -1, 90] │
│       ┆ 者            ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 11    ┆ 冰心之魂      ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [41, 2, 240] │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 15    ┆ 索西雅的灾星  ┆ {"[grade]":   ┆ [achievement] ┆ Y          ┆ [condition   ┆ [140, 2, 1]  │
│       ┆               ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 22    ┆ 调查GBL神殿   ┆ {"[grade]":   ┆ [epic]        ┆ W          ┆ [condition   ┆ [21, -1]     │
│       ┆               ┆ ["[epic]"],   ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ "[diff…       ┆               ┆            ┆              ┆              │
│ …     ┆ …             ┆ …             ┆ …             ┆ …          ┆ …            ┆ …            │
│ 20728 ┆ 虚祖圣地 -    ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [condition   ┆ [3538, -1,   │
│       ┆ 与巨龙战斗    ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 1]           │
│       ┆ (2/2)         ┆ t]"],…        ┆               ┆            ┆              ┆              │
│ 20729 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3536, 2, 1] │
│       ┆ 念气修炼场    ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20730 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3537, 2, 1] │
│       ┆ 念气洞穴深处  ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆              │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20731 ┆ 协同 :        ┆ {"[grade]":   ┆ [daily]       ┆ D          ┆ [condition   ┆ [3538, -1,   │
│       ┆ 巨龙盘踞之地  ┆ ["[daily]"],  ┆               ┆            ┆ under clear] ┆ 1]           │
│       ┆               ┆ "[dif…        ┆               ┆            ┆              ┆              │
│ 20735 ┆ [限时]极限挑  ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [condition   ┆ [3539, 0,    │
│       ┆ 战 - 屠龙     ┆ ["[achievemen ┆               ┆            ┆ under clear] ┆ 360]         │
│       ┆               ┆ t]"],…        ┆               ┆            ┆              ┆              │
└───────┴───────────────┴───────────────┴───────────────┴────────────┴──────────────┴──────────────┘

In [23]:
df.filter(pl.col('quest_type') == '[hunt enemy]')

shape: (520, 7)
┌──────┬───────────────┬───────────────┬───────────────┬────────────┬──────────────┬───────────────┐
│ id   ┆ name          ┆ json          ┆ grade         ┆ difficulty ┆ quest_type   ┆ int_data      │
│ ---  ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---          ┆ ---           │
│ i64  ┆ str           ┆ str           ┆ str           ┆ str        ┆ str          ┆ list[i64]     │
╞══════╪═══════════════╪═══════════════╪═══════════════╪════════════╪══════════════╪═══════════════╡
│ 64   ┆ 迷妄之塔      ┆ {"[grade]":   ┆ [epic]        ┆ Y          ┆ [hunt enemy] ┆ [11001, -1, … │
│      ┆               ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 1]            │
│      ┆               ┆ "[igno…       ┆               ┆            ┆              ┆               │
│ 65   ┆ 被遗忘者之塔  ┆ {"[grade]":   ┆ [epic]        ┆ Y          ┆ [hunt enemy] ┆ [11001, -1, … │
│      ┆               ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 1]            │
│      ┆               ┆ "[igno…       ┆               ┆            ┆              ┆               │
│ 557  ┆ 宿敌          ┆ {"[grade]":   ┆ [common       ┆ C          ┆ [hunt enemy] ┆ [23, 1, … 1]  │
│      ┆               ┆ ["[common     ┆ unique]       ┆            ┆              ┆               │
│      ┆               ┆ unique]"…     ┆               ┆            ┆              ┆               │
│ 2603 ┆ 深渊派对Ep1 - ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [hunt enemy] ┆ [44, 2, … 1]  │
│      ┆ 渐渐浮现的真  ┆ ["[achievemen ┆               ┆            ┆              ┆               │
│      ┆ 相            ┆ t]"],…        ┆               ┆            ┆              ┆               │
│ 2610 ┆ 深渊派对Ep2 - ┆ {"[grade]":   ┆ [achievement] ┆ D          ┆ [hunt enemy] ┆ [50, 2, … 1]  │
│      ┆ 邪恶来临      ┆ ["[achievemen ┆               ┆            ┆              ┆               │
│      ┆               ┆ t]"],…        ┆               ┆            ┆              ┆               │
│ …    ┆ …             ┆ …             ┆ …             ┆ …          ┆ …            ┆ …             │
│ 4573 ┆ 消灭玛格尼    ┆ {"[grade]":   ┆ [epic]        ┆ Y          ┆ [hunt enemy] ┆ [102, -1, …   │
│      ┆               ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 10]           │
│      ┆               ┆ "[diff…       ┆               ┆            ┆              ┆               │
│ 4574 ┆ 关闭起重装置  ┆ {"[grade]":   ┆ [epic]        ┆ Z          ┆ [hunt enemy] ┆ [102, -1, …   │
│      ┆               ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 1]            │
│      ┆               ┆ "[diff…       ┆               ┆            ┆              ┆               │
│ 4575 ┆ 熔弹萨缪尔    ┆ {"[grade]":   ┆ [epic]        ┆ X          ┆ [hunt enemy] ┆ [102, -1, …   │
│      ┆               ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 3]            │
│      ┆               ┆ "[diff…       ┆               ┆            ┆              ┆               │
│ 4581 ┆ 能源中心的负  ┆ {"[grade]":   ┆ [epic]        ┆ W          ┆ [hunt enemy] ┆ [103, -1, …   │
│      ┆ 责人          ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 1]            │
│      ┆               ┆ "[diff…       ┆               ┆            ┆              ┆               │
│ 4583 ┆ 消灭闪电之帕  ┆ {"[grade]":   ┆ [epic]        ┆ Z          ┆ [hunt enemy] ┆ [103, -1, …   │
│      ┆ 特奡          ┆ ["[epic]"],   ┆               ┆            ┆              ┆ 3]            │
│      ┆               ┆ "[diff…       ┆               ┆            ┆              ┆               │
└──────┴───────────────┴───────────────┴───────────────┴────────────┴──────────────┴───────────────┘